export default {
  lorem: [
    'Nulla semper ipsum consequat magna vestibulum ornare. Donec dictum nibh vitae orci pellentesque rhoncus a sed dolor. Integer non suscipit ex. Quisque tristique est ac vulputate dictum. Vestibulum tristique ante in nulla vulputate interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi sed ex elementum, consectetur leo et, auctor augue. Maecenas tincidunt vitae libero non lobortis',
    'Vivamus a quam consectetur, egestas orci ac, dapibus ante. Vivamus eget tortor venenatis, placerat neque quis, commodo neque. Sed et auctor ligula, in congue lectus. Aenean tempus convallis lectus a tristique. Integer luctus tincidunt diam. Aliquam erat volutpat. Mauris risus est, congue utsuscipit nec, consequat imperdiet purus. Nunc metus neque, viverra id dolor nec, consectetur mattis lectus. Cras odio ex, rutrum id enim a, congue pellentesque erat. Nam non ultrices tellus. Sed eget odio nec enim vulputate volutpat sit amet mattis odio. Sed sodales, odio quis venenatis efficitur,tortor sapien tincidunt tortor, quis venenatis augue massa eu massa. Praesent suscipit, velit non fermentum accumsan, felis lorem vulputate purus, a consequat lacus elit in nulla. Morbi ac fringilla tortor. Mauris fermentum ac ipsum a posuere. Duis mattis mollis mauris et dictum.',
    'Phasellus placerat aliquam porttitor. Donec dolor ipsum, gravida egestas fringilla dapibus, dapibus ac sapien. Praesent lacus erat, placerat quis cursus ut, blandit laoreet felis. Vivamus pharetra quam nibh, ac cursus nulla porttitor a. Quisque non dui nisl. In ultricies quis lectus ac cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec vulputate, nulla et dictum venenatis, ipsum orci luctus dolor, id fringilla diam dui sit amet diam. Vestibulum ut sapien blandit, dictum neque eu, gravida lorem.',
    'Sed porta mattis nisl sed mattis. Aenean massa sem, vestibulum sed orci ut, tincidunt lobortis neque. Phasellus hendrerit dictum ipsum et posuere. Proin lobortis eget velit at ultrices. Maecenas laoreet laoreet odio, quis rutrum enim varius vel. Nunc venenatis purus sit amet diam porta aliquet. Suspendisse imperdiet, urna eu eleifend pulvinar, diam neque pretium mi, in convallis enim purus a ante. Nunc erat lorem, aliquam vitae interdum vel, consequat sit amet ipsum. Nullam hendrerit porttitor consectetur. Curabitur libero risus, elementum ac risus scelerisque, tempus vehicula risus. Aliquam condimentum vulputate laoreet. Aliquam consequat quis ante sed tincidunt. Cras dictum odio id efficitur pretium. Curabitur aliquet feugiat bibendum. Aenean bibendum lorem eget elit tincidunt, porttitor egestas purus lobortis. Quisque ut arcu metus.',
    'Nulla semper ipsum consequat magna vestibulum ornare. Donec dictum nibh vitae orci pellentesque rhoncus a sed dolor. Integer non suscipit ex. Quisque tristique est ac vulputate dictum. Vestibulum tristique ante in nulla vulputate interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi sed ex elementum, consectetur leo et, auctor augue. Maecenas tincidunt vitae libero non lobortis',
  ],
}
